In [1]:
import pandas as pd

In [2]:
d = {'Id':[1,2,3,4,5,6,7,2,9,10,11],
     'Name':['Smith','Scott','Allen','Black','Miller','Martin','Allen','Scott','King','Clerk','Adams'],
     'Sal':[5000,3000,7000,3000,5000,6000,7000,3000,15000,6000,3000],
     'Hiredate':['05-jan-2005','07-feb-2003','17-apr-2007','5-jan-2005','01-feb-2002','01-feb-2002','17-apr-2007','07-feb-2003','11-feb-2000','05-mar-2003','16-feb-2002'],
     'Deptno':[10.0,20.0,10.0,30.0,10.0,20.0,10.0,20.0,20.0,30.0,10.0],
     'Comm':[None,None,None,1000,1000,2000,None,None,5000,None,None]}

In [3]:
df = pd.DataFrame(d)
df

    Id    Name    Sal     Hiredate  Deptno    Comm
0    1   Smith   5000  05-jan-2005    10.0     NaN
1    2   Scott   3000  07-feb-2003    20.0     NaN
2    3   Allen   7000  17-apr-2007    10.0     NaN
3    4   Black   3000   5-jan-2005    30.0  1000.0
4    5  Miller   5000  01-feb-2002    10.0  1000.0
5    6  Martin   6000  01-feb-2002    20.0  2000.0
6    7   Allen   7000  17-apr-2007    10.0     NaN
7    2   Scott   3000  07-feb-2003    20.0     NaN
8    9    King  15000  11-feb-2000    20.0  5000.0
9   10   Clerk   6000  05-mar-2003    30.0     NaN
10  11   Adams   3000  16-feb-2002    10.0     NaN

In [4]:
df.shape
#11=> row,  6=> coloum
#shape is an attribute(variable) of df which holds the tuple(tuple -->n_rows,n_coloum)
#df .means table

(11, 6)

In [5]:
df.head()

   Id    Name   Sal     Hiredate  Deptno    Comm
0   1   Smith  5000  05-jan-2005    10.0     NaN
1   2   Scott  3000  07-feb-2003    20.0     NaN
2   3   Allen  7000  17-apr-2007    10.0     NaN
3   4   Black  3000   5-jan-2005    30.0  1000.0
4   5  Miller  5000  01-feb-2002    10.0  1000.0

In [6]:
df.head(n=3)

   Id   Name   Sal     Hiredate  Deptno  Comm
0   1  Smith  5000  05-jan-2005    10.0   NaN
1   2  Scott  3000  07-feb-2003    20.0   NaN
2   3  Allen  7000  17-apr-2007    10.0   NaN

In [7]:
df.tail()

    Id   Name    Sal     Hiredate  Deptno    Comm
6    7  Allen   7000  17-apr-2007    10.0     NaN
7    2  Scott   3000  07-feb-2003    20.0     NaN
8    9   King  15000  11-feb-2000    20.0  5000.0
9   10  Clerk   6000  05-mar-2003    30.0     NaN
10  11  Adams   3000  16-feb-2002    10.0     NaN

In [8]:
df.tail(n=3)

    Id   Name    Sal     Hiredate  Deptno    Comm
8    9   King  15000  11-feb-2000    20.0  5000.0
9   10  Clerk   6000  05-mar-2003    30.0     NaN
10  11  Adams   3000  16-feb-2002    10.0     NaN

head():return top n_rows

tail():return bottom n_rows

### Selecting the coloums

In [9]:
df['Name']

0      Smith
1      Scott
2      Allen
3      Black
4     Miller
5     Martin
6      Allen
7      Scott
8       King
9      Clerk
10     Adams
Name: Name, dtype: str

In [10]:
df[['Name','Sal','Deptno']]
#to select the multiple coloum we need to use df[list_of_col_names]

      Name    Sal  Deptno
0    Smith   5000    10.0
1    Scott   3000    20.0
2    Allen   7000    10.0
3    Black   3000    30.0
4   Miller   5000    10.0
5   Martin   6000    20.0
6    Allen   7000    10.0
7    Scott   3000    20.0
8     King  15000    20.0
9    Clerk   6000    30.0
10   Adams   3000    10.0

df.loc[row_index,coloum_name]

df.loc[list_of_row_index,list_of_coloum_name]

coloum_name/coloum_names are optional (by default it select all the coloum)

df.loc[filter_conditon,coloum_name/coloum_names]

In [11]:
df.loc[3]

Id                   4
Name             Black
Sal               3000
Hiredate    5-jan-2005
Deptno            30.0
Comm            1000.0
Name: 3, dtype: object

In [12]:
df.loc[3,'Name']

'Black'

In [13]:
df.loc[[3,4]]

   Id    Name   Sal     Hiredate  Deptno    Comm
3   4   Black  3000   5-jan-2005    30.0  1000.0
4   5  Miller  5000  01-feb-2002    10.0  1000.0

In [14]:
df.loc[[3,4],'Name']

3     Black
4    Miller
Name: Name, dtype: str

In [15]:
df.loc[[3,4],['Name','Sal']]

     Name   Sal
3   Black  3000
4  Miller  5000

In [16]:
df.loc[df['Sal']>3000]

   Id    Name    Sal     Hiredate  Deptno    Comm
0   1   Smith   5000  05-jan-2005    10.0     NaN
2   3   Allen   7000  17-apr-2007    10.0     NaN
4   5  Miller   5000  01-feb-2002    10.0  1000.0
5   6  Martin   6000  01-feb-2002    20.0  2000.0
6   7   Allen   7000  17-apr-2007    10.0     NaN
8   9    King  15000  11-feb-2000    20.0  5000.0
9  10   Clerk   6000  05-mar-2003    30.0     NaN

In [17]:
df.loc[df['Sal']>5000]

   Id    Name    Sal     Hiredate  Deptno    Comm
2   3   Allen   7000  17-apr-2007    10.0     NaN
5   6  Martin   6000  01-feb-2002    20.0  2000.0
6   7   Allen   7000  17-apr-2007    10.0     NaN
8   9    King  15000  11-feb-2000    20.0  5000.0
9  10   Clerk   6000  05-mar-2003    30.0     NaN

In [18]:
df.loc[df['Sal']>3000,['Name','Deptno']]

     Name  Deptno
0   Smith    10.0
2   Allen    10.0
4  Miller    10.0
5  Martin    20.0
6   Allen    10.0
8    King    20.0
9   Clerk    30.0

In [19]:
#inside the loc[]attribute
# and,or,not =>(&,/,~)
#every condition must be written inside the parenthesis

df.loc[(df['Sal']==3000) | (df['Sal']==5000)]

    Id    Name   Sal     Hiredate  Deptno    Comm
0    1   Smith  5000  05-jan-2005    10.0     NaN
1    2   Scott  3000  07-feb-2003    20.0     NaN
3    4   Black  3000   5-jan-2005    30.0  1000.0
4    5  Miller  5000  01-feb-2002    10.0  1000.0
7    2   Scott  3000  07-feb-2003    20.0     NaN
10  11   Adams  3000  16-feb-2002    10.0     NaN

In [20]:
df.loc[df['Sal'] .isin([3000,5000])]

    Id    Name   Sal     Hiredate  Deptno    Comm
0    1   Smith  5000  05-jan-2005    10.0     NaN
1    2   Scott  3000  07-feb-2003    20.0     NaN
3    4   Black  3000   5-jan-2005    30.0  1000.0
4    5  Miller  5000  01-feb-2002    10.0  1000.0
7    2   Scott  3000  07-feb-2003    20.0     NaN
10  11   Adams  3000  16-feb-2002    10.0     NaN

###  Checking for duplicates(duplicate rows)

In [21]:
df.duplicated()
#series of boolean

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
dtype: bool

In [22]:
df.duplicated().any()
#employee data frame has duplicates

np.True_

In [23]:
df.duplicated().sum()
#employee data frame has only 1 duplicate rows

np.int64(1)

## removing the duplicate row

In [24]:
#keeping the first occurance 
df.drop_duplicates(keep='first')
#keeping the last occurance
df.drop_duplicates(keep='last')

df.drop_duplicates(keep=False)

    Id    Name    Sal     Hiredate  Deptno    Comm
0    1   Smith   5000  05-jan-2005    10.0     NaN
2    3   Allen   7000  17-apr-2007    10.0     NaN
3    4   Black   3000   5-jan-2005    30.0  1000.0
4    5  Miller   5000  01-feb-2002    10.0  1000.0
5    6  Martin   6000  01-feb-2002    20.0  2000.0
6    7   Allen   7000  17-apr-2007    10.0     NaN
8    9    King  15000  11-feb-2000    20.0  5000.0
9   10   Clerk   6000  05-mar-2003    30.0     NaN
10  11   Adams   3000  16-feb-2002    10.0     NaN

In [25]:
df=df.drop_duplicates(keep='first')

In [26]:
df=df.drop_duplicates(keep='last')

In [27]:
df

    Id    Name    Sal     Hiredate  Deptno    Comm
0    1   Smith   5000  05-jan-2005    10.0     NaN
1    2   Scott   3000  07-feb-2003    20.0     NaN
2    3   Allen   7000  17-apr-2007    10.0     NaN
3    4   Black   3000   5-jan-2005    30.0  1000.0
4    5  Miller   5000  01-feb-2002    10.0  1000.0
5    6  Martin   6000  01-feb-2002    20.0  2000.0
6    7   Allen   7000  17-apr-2007    10.0     NaN
8    9    King  15000  11-feb-2000    20.0  5000.0
9   10   Clerk   6000  05-mar-2003    30.0     NaN
10  11   Adams   3000  16-feb-2002    10.0     NaN

### Resetting the index

In [28]:
df.reset_index()

   index  Id    Name    Sal     Hiredate  Deptno    Comm
0      0   1   Smith   5000  05-jan-2005    10.0     NaN
1      1   2   Scott   3000  07-feb-2003    20.0     NaN
2      2   3   Allen   7000  17-apr-2007    10.0     NaN
3      3   4   Black   3000   5-jan-2005    30.0  1000.0
4      4   5  Miller   5000  01-feb-2002    10.0  1000.0
5      5   6  Martin   6000  01-feb-2002    20.0  2000.0
6      6   7   Allen   7000  17-apr-2007    10.0     NaN
7      8   9    King  15000  11-feb-2000    20.0  5000.0
8      9  10   Clerk   6000  05-mar-2003    30.0     NaN
9     10  11   Adams   3000  16-feb-2002    10.0     NaN

In [29]:
df=df.reset_index(drop=True)
# it reset the index (0 to n)and drop= true will remove the old_index

In [30]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm
0   1   Smith   5000  05-jan-2005    10.0     NaN
1   2   Scott   3000  07-feb-2003    20.0     NaN
2   3   Allen   7000  17-apr-2007    10.0     NaN
3   4   Black   3000   5-jan-2005    30.0  1000.0
4   5  Miller   5000  01-feb-2002    10.0  1000.0
5   6  Martin   6000  01-feb-2002    20.0  2000.0
6   7   Allen   7000  17-apr-2007    10.0     NaN
7   9    King  15000  11-feb-2000    20.0  5000.0
8  10   Clerk   6000  05-mar-2003    30.0     NaN
9  11   Adams   3000  16-feb-2002    10.0     NaN

## information about the dataframe

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        10 non-null     int64
 1   Name      10 non-null     str
 2   Sal       10 non-null     int64
 3   Hiredate  10 non-null     str
 4   Deptno    10 non-null     float64
 5   Comm      4 non-null      float64
dtypes: float64(2), int64(2), str(2)
memory usage: 608.0 bytes

### Statistical description for numrical column

In [32]:
df.describe()
#dummy data

              Id           Sal     Deptno         Comm
count  10.000000     10.000000  10.000000     4.000000
mean    5.800000   6000.000000  17.000000  2250.000000
std     3.425395   3527.668415   8.232726  1892.969449
min     1.000000   3000.000000  10.000000  1000.000000
25%     3.250000   3500.000000  10.000000  1000.000000
50%     5.500000   5500.000000  15.000000  1500.000000
75%     8.500000   6750.000000  20.000000  2750.000000
max    11.000000  15000.000000  30.000000  5000.000000

## finding  no_of_non_null values in commission column

In [33]:
df['Comm'].isnull()

0     True
1     True
2     True
3    False
4    False
5    False
6     True
7    False
8     True
9     True
Name: Comm, dtype: bool

In [34]:
df['Comm'].isnull().sum()

np.int64(6)

### filling the missing values

In [35]:
df['Comm']

0       NaN
1       NaN
2       NaN
3    1000.0
4    1000.0
5    2000.0
6       NaN
7    5000.0
8       NaN
9       NaN
Name: Comm, dtype: float64

In [36]:
df['Comm'].fillna(0)
#fills zero where ever it finding missing value

0       0.0
1       0.0
2       0.0
3    1000.0
4    1000.0
5    2000.0
6       0.0
7    5000.0
8       0.0
9       0.0
Name: Comm, dtype: float64

In [37]:
df['Comm']=df['Comm'].fillna(0)

In [38]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm
0   1   Smith   5000  05-jan-2005    10.0     0.0
1   2   Scott   3000  07-feb-2003    20.0     0.0
2   3   Allen   7000  17-apr-2007    10.0     0.0
3   4   Black   3000   5-jan-2005    30.0  1000.0
4   5  Miller   5000  01-feb-2002    10.0  1000.0
5   6  Martin   6000  01-feb-2002    20.0  2000.0
6   7   Allen   7000  17-apr-2007    10.0     0.0
7   9    King  15000  11-feb-2000    20.0  5000.0
8  10   Clerk   6000  05-mar-2003    30.0     0.0
9  11   Adams   3000  16-feb-2002    10.0     0.0

### creating new column

In [39]:
df['Sal']+df['Comm']

0     5000.0
1     3000.0
2     7000.0
3     4000.0
4     6000.0
5     8000.0
6     7000.0
7    20000.0
8     6000.0
9     3000.0
dtype: float64

In [40]:
#1.
df['Income']=df['Sal'] + df['Comm']
#column & values

In [41]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income
0   1   Smith   5000  05-jan-2005    10.0     0.0   5000.0
1   2   Scott   3000  07-feb-2003    20.0     0.0   3000.0
2   3   Allen   7000  17-apr-2007    10.0     0.0   7000.0
3   4   Black   3000   5-jan-2005    30.0  1000.0   4000.0
4   5  Miller   5000  01-feb-2002    10.0  1000.0   6000.0
5   6  Martin   6000  01-feb-2002    20.0  2000.0   8000.0
6   7   Allen   7000  17-apr-2007    10.0     0.0   7000.0
7   9    King  15000  11-feb-2000    20.0  5000.0  20000.0
8  10   Clerk   6000  05-mar-2003    30.0     0.0   6000.0
9  11   Adams   3000  16-feb-2002    10.0     0.0   3000.0

In [42]:
#2.
pd.cut(df['Income'],bins=[3000,7000,16000,20000],labels=['Low pay','Medium pay','High pay'],include_lowest=True)

0       Low pay
1       Low pay
2       Low pay
3       Low pay
4       Low pay
5    Medium pay
6       Low pay
7      High pay
8       Low pay
9       Low pay
Name: Income, dtype: category
Categories (3, str): ['Low pay' < 'Medium pay' < 'High pay']

In [43]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income
0   1   Smith   5000  05-jan-2005    10.0     0.0   5000.0
1   2   Scott   3000  07-feb-2003    20.0     0.0   3000.0
2   3   Allen   7000  17-apr-2007    10.0     0.0   7000.0
3   4   Black   3000   5-jan-2005    30.0  1000.0   4000.0
4   5  Miller   5000  01-feb-2002    10.0  1000.0   6000.0
5   6  Martin   6000  01-feb-2002    20.0  2000.0   8000.0
6   7   Allen   7000  17-apr-2007    10.0     0.0   7000.0
7   9    King  15000  11-feb-2000    20.0  5000.0  20000.0
8  10   Clerk   6000  05-mar-2003    30.0     0.0   6000.0
9  11   Adams   3000  16-feb-2002    10.0     0.0   3000.0

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        10 non-null     int64
 1   Name      10 non-null     str
 2   Sal       10 non-null     int64
 3   Hiredate  10 non-null     str
 4   Deptno    10 non-null     float64
 5   Comm      10 non-null     float64
 6   Income    10 non-null     float64
dtypes: float64(3), int64(2), str(2)
memory usage: 688.0 bytes

### type casting

In [45]:
pd.to_datetime(df['Hiredate'])

C:\Users\azadh\AppData\Local\Temp\ipykernel_2196\2993138014.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df['Hiredate'])

0   2005-01-05
1   2003-02-07
2   2007-04-17
3   2005-01-05
4   2002-02-01
5   2002-02-01
6   2007-04-17
7   2000-02-11
8   2003-03-05
9   2002-02-16
Name: Hiredate, dtype: datetime64[us]

In [46]:
df['Deptno']

0    10.0
1    20.0
2    10.0
3    30.0
4    10.0
5    20.0
6    10.0
7    20.0
8    30.0
9    10.0
Name: Deptno, dtype: float64

In [47]:
df['Deptno'].astype(int)

0    10
1    20
2    10
3    30
4    10
5    20
6    10
7    20
8    30
9    10
Name: Deptno, dtype: int64

In [48]:
df['Deptno']=df['Deptno'].astype(int)

In [49]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income
0   1   Smith   5000  05-jan-2005      10     0.0   5000.0
1   2   Scott   3000  07-feb-2003      20     0.0   3000.0
2   3   Allen   7000  17-apr-2007      10     0.0   7000.0
3   4   Black   3000   5-jan-2005      30  1000.0   4000.0
4   5  Miller   5000  01-feb-2002      10  1000.0   6000.0
5   6  Martin   6000  01-feb-2002      20  2000.0   8000.0
6   7   Allen   7000  17-apr-2007      10     0.0   7000.0
7   9    King  15000  11-feb-2000      20  5000.0  20000.0
8  10   Clerk   6000  05-mar-2003      30     0.0   6000.0
9  11   Adams   3000  16-feb-2002      10     0.0   3000.0

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        10 non-null     int64
 1   Name      10 non-null     str
 2   Sal       10 non-null     int64
 3   Hiredate  10 non-null     str
 4   Deptno    10 non-null     int64
 5   Comm      10 non-null     float64
 6   Income    10 non-null     float64
dtypes: float64(2), int64(3), str(2)
memory usage: 688.0 bytes

In [51]:
##PARAMETER 1.raise2.coerce 3.ignore assignment

In [52]:
df['age']=[25,27,25,26,23,24,27,23,19,42]

In [53]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income  age
0   1   Smith   5000  05-jan-2005      10     0.0   5000.0   25
1   2   Scott   3000  07-feb-2003      20     0.0   3000.0   27
2   3   Allen   7000  17-apr-2007      10     0.0   7000.0   25
3   4   Black   3000   5-jan-2005      30  1000.0   4000.0   26
4   5  Miller   5000  01-feb-2002      10  1000.0   6000.0   23
5   6  Martin   6000  01-feb-2002      20  2000.0   8000.0   24
6   7   Allen   7000  17-apr-2007      10     0.0   7000.0   27
7   9    King  15000  11-feb-2000      20  5000.0  20000.0   23
8  10   Clerk   6000  05-mar-2003      30     0.0   6000.0   19
9  11   Adams   3000  16-feb-2002      10     0.0   3000.0   42

In [54]:
df['age']=df['age']=[25,27,25,26,23,24,27,23,19,42]

In [55]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income  age
0   1   Smith   5000  05-jan-2005      10     0.0   5000.0   25
1   2   Scott   3000  07-feb-2003      20     0.0   3000.0   27
2   3   Allen   7000  17-apr-2007      10     0.0   7000.0   25
3   4   Black   3000   5-jan-2005      30  1000.0   4000.0   26
4   5  Miller   5000  01-feb-2002      10  1000.0   6000.0   23
5   6  Martin   6000  01-feb-2002      20  2000.0   8000.0   24
6   7   Allen   7000  17-apr-2007      10     0.0   7000.0   27
7   9    King  15000  11-feb-2000      20  5000.0  20000.0   23
8  10   Clerk   6000  05-mar-2003      30     0.0   6000.0   19
9  11   Adams   3000  16-feb-2002      10     0.0   3000.0   42

In [56]:
# to create age_category we can use either pd.cut() or df['age'].apply()
# step1: create user_define function()
# step:2 pass the user_define function to apply() as a argument

def age_category(a):
    if a >= 18 and a<=25:
        return 'Teen'
    elif a >= 26 and a <=59:
        return 'Adult'
    elif a >=60 and a <= 100:
        return 'Senior'

In [57]:
df['age'].apply(age_category)

#apply() method taken the value from age_col and pass it to age_category function . it age value satisfied the condition then it return the els none(default)(teen, adult,senior)

0     Teen
1    Adult
2     Teen
3    Adult
4     Teen
5     Teen
6    Adult
7     Teen
8     Teen
9    Adult
Name: age, dtype: str

In [58]:
df['age_category']=df['age'].apply(age_category)

In [59]:
df

   Id    Name    Sal     Hiredate  Deptno    Comm   Income  age age_category
0   1   Smith   5000  05-jan-2005      10     0.0   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20     0.0   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10     0.0   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30  1000.0   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10  1000.0   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20  2000.0   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10     0.0   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  5000.0  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30     0.0   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10     0.0   3000.0   42        Adult

### droping the columns/rows

In [60]:
df.drop(columns=['Comm'])

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

In [61]:
df=df.drop(columns=['Comm'])

In [62]:
df

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

In [63]:
df.drop(index=[2,4,9])

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen

In [64]:
df
#  10 rows ( becasue df is not updated)

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            10 non-null     int64
 1   Name          10 non-null     str
 2   Sal           10 non-null     int64
 3   Hiredate      10 non-null     str
 4   Deptno        10 non-null     int64
 5   Income        10 non-null     float64
 6   age           10 non-null     int64
 7   age_category  10 non-null     str
dtypes: float64(1), int64(4), str(3)
memory usage: 768.0 bytes

### updating the age and age_category value using loc[]

In [66]:
df.loc[ df['age']==17,'age']= 27

In [67]:
df

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

In [68]:
df.loc[ df['age_category'] == None ,'age_category'] ='Adult'

In [69]:
df

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

In [70]:
df.loc[ df['age_category'].isnull(),'age_category'] ='Adult'

In [71]:
df

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

### drop the allen and king details

In [72]:
df.loc[df['Name'].isin(['Allen','King'])]

   Id   Name    Sal     Hiredate  Deptno   Income  age age_category
2   3  Allen   7000  17-apr-2007      10   7000.0   25         Teen
6   7  Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9   King  15000  11-feb-2000      20  20000.0   23         Teen

In [73]:
df.loc[df['Name'].isin(['Allen','King'])].index

Index([2, 6, 7], dtype='int64')

In [74]:
idx=df.loc[df['Name'].isin(['Allen','King'])].index

In [75]:
idx

Index([2, 6, 7], dtype='int64')

In [76]:
df.drop(index=idx)
#3 rows are removed

   Id    Name   Sal     Hiredate  Deptno  Income  age age_category
0   1   Smith  5000  05-jan-2005      10  5000.0   25         Teen
1   2   Scott  3000  07-feb-2003      20  3000.0   27        Adult
3   4   Black  3000   5-jan-2005      30  4000.0   26        Adult
4   5  Miller  5000  01-feb-2002      10  6000.0   23         Teen
5   6  Martin  6000  01-feb-2002      20  8000.0   24         Teen
8  10   Clerk  6000  05-mar-2003      30  6000.0   19         Teen
9  11   Adams  3000  16-feb-2002      10  3000.0   42        Adult

In [77]:
df
#10 row (droped rows are updated to df)

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

### depatment wise no_of employee

In [78]:
#method 1.

df['Deptno']

0    10
1    20
2    10
3    30
4    10
5    20
6    10
7    20
8    30
9    10
Name: Deptno, dtype: int64

In [79]:
df['Deptno'].value_counts()

Deptno
10    5
20    3
30    2
Name: count, dtype: int64

In [80]:
df['Deptno'].value_counts().index

Index([10, 20, 30], dtype='int64', name='Deptno')

In [81]:
df['Deptno'].value_counts().values

array([5, 3, 2])

In [82]:
df['Deptno'].value_counts().idxmax()

np.int64(10)

In [83]:
df['Deptno'].value_counts().idxmin

<bound method Series.idxmin of Deptno
10    5
20    3
30    2
Name: count, dtype: int64>

In [84]:
df

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
0   1   Smith   5000  05-jan-2005      10   5000.0   25         Teen
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
2   3   Allen   7000  17-apr-2007      10   7000.0   25         Teen
3   4   Black   3000   5-jan-2005      30   4000.0   26        Adult
4   5  Miller   5000  01-feb-2002      10   6000.0   23         Teen
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
6   7   Allen   7000  17-apr-2007      10   7000.0   27        Adult
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen
8  10   Clerk   6000  05-mar-2003      30   6000.0   19         Teen
9  11   Adams   3000  16-feb-2002      10   3000.0   42        Adult

### groping and aggregating

In [85]:
df['Deptno']

0    10
1    20
2    10
3    30
4    10
5    20
6    10
7    20
8    30
9    10
Name: Deptno, dtype: int64

In [86]:
df.groupby(['Deptno'])

In [87]:
g=df.groupby('Deptno')

In [88]:
g
# G is object by group by()

In [89]:
# 1.
g.groups     #group is an attribute

{10: [0, 2, 4, 6, 9], 20: [1, 5, 7], 30: [3, 8]}

In [90]:
#2.
g.get_group(20)

   Id    Name    Sal     Hiredate  Deptno   Income  age age_category
1   2   Scott   3000  07-feb-2003      20   3000.0   27        Adult
5   6  Martin   6000  01-feb-2002      20   8000.0   24         Teen
7   9    King  15000  11-feb-2000      20  20000.0   23         Teen

In [91]:
g.agg({'Sal':sum})

          Sal
Deptno
10      27000
20      24000
30       9000

In [92]:
#4.
g.agg({'Sal':['mean','sum']})

           Sal
          mean    sum
Deptno
10      5400.0  27000
20      8000.0  24000
30      4500.0   9000

In [93]:
g.agg({'Sal':['max','min'],'age':'max'})

          Sal       age
          max   min max
Deptno
10       7000  3000  42
20      15000  3000  27
30       6000  3000  26

### create  the emp1 dataframe

In [94]:
df.columns

Index(['Id', 'Name', 'Sal', 'Hiredate', 'Deptno', 'Income', 'age',
       'age_category'],
      dtype='str')

In [95]:
emp1 = pd.DataFrame({'id':[12,13],
                     'Name':['abc','xyz'],
                     'Sal':[7000,3000],
                     'Hiredate':[pd.to_datetime('02-feb-2002'), pd.to_datetime('03-mar-2001')],
                     'Deptno':[10]*2,
                     'sal_grade':['medium pay','low pay'],
                     'comm':[None,500],
                     'age':[22,23],
                     'age_category':['teen']*2,
                     'income':[7000,3500]
})

In [96]:
emp1

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income
0,12,abc,7000,2002-02-02,10,medium pay,NaN,22,teen,7000
1,13,xyz,3000,2001-03-03,10,low pay,500.0,23,teen,3500

In [97]:
pd.concat([df,emp1])

,Id,Name,Sal,Hiredate,Deptno,Income,age,age_category,id,sal_grade,comm,income
0,1.0,Smith,5000,05-jan-2005,10,5000.0,25,Teen,NaN,NaN,NaN,NaN
1,2.0,Scott,3000,07-feb-2003,20,3000.0,27,Adult,NaN,NaN,NaN,NaN
2,3.0,Allen,7000,17-apr-2007,10,7000.0,25,Teen,NaN,NaN,NaN,NaN
3,4.0,Black,3000,5-jan-2005,30,4000.0,26,Adult,NaN,NaN,NaN,NaN
4,5.0,Miller,5000,01-feb-2002,10,6000.0,23,Teen,NaN,NaN,NaN,NaN
5,6.0,Martin,6000,01-feb-2002,20,8000.0,24,Teen,NaN,NaN,NaN,NaN
6,7.0,Allen,7000,17-apr-2007,10,7000.0,27,Adult,NaN,NaN,NaN,NaN
7,9.0,King,15000,11-feb-2000,20,20000.0,23,Teen,NaN,NaN,NaN,NaN
8,10.0,Clerk,6000,05-mar-2003,30,6000.0,19,Teen,NaN,NaN,NaN,NaN
9,11.0,Adams,3000,16-feb-2002,10,3000.0,42,Adult,NaN,NaN,NaN,NaN
0,NaN,abc,7000,2002-02-02 00:00:00,10,NaN,22,teen,12.0,medium pay,NaN,7000.0
1,NaN,xyz,3000,2001-03-03 00:00:00,10,NaN,23,teen,13.0,low pay,500.0,3500.0

In [98]:
Dept= pd.DataFrame({
    'Deptno':[10.0,20.0],
    'dname':['abc','cbz'],
    'loc':['bal','mum']
})
Dept

   Deptno dname  loc
0    10.0   abc  bal
1    20.0   cbz  mum

In [99]:
pd.concat([emp1,Dept])

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12.0,abc,7000.0,2002-02-02,10.0,medium pay,NaN,22.0,teen,7000.0,NaN,NaN
1,13.0,xyz,3000.0,2001-03-03,10.0,low pay,500.0,23.0,teen,3500.0,NaN,NaN
0,NaN,NaN,NaN,NaT,10.0,NaN,NaN,NaN,NaN,NaN,abc,bal
1,NaN,NaN,NaN,NaT,20.0,NaN,NaN,NaN,NaN,NaN,cbz,mum

In [100]:
pd.concat([emp1,Dept], axis=0)

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12.0,abc,7000.0,2002-02-02,10.0,medium pay,NaN,22.0,teen,7000.0,NaN,NaN
1,13.0,xyz,3000.0,2001-03-03,10.0,low pay,500.0,23.0,teen,3500.0,NaN,NaN
0,NaN,NaN,NaN,NaT,10.0,NaN,NaN,NaN,NaN,NaN,abc,bal
1,NaN,NaN,NaN,NaT,20.0,NaN,NaN,NaN,NaN,NaN,cbz,mum

In [101]:
pd.concat([emp1,Dept], axis=1)

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,Deptno,dname,loc
0,12,abc,7000,2002-02-02,10,medium pay,NaN,22,teen,7000,10.0,abc,bal
1,13,xyz,3000,2001-03-03,10,low pay,500.0,23,teen,3500,20.0,cbz,mum

In [102]:
pd.merge(emp1,Dept , on='Deptno', how='left')

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12,abc,7000,2002-02-02,10,medium pay,NaN,22,teen,7000,abc,bal
1,13,xyz,3000,2001-03-03,10,low pay,500.0,23,teen,3500,abc,bal

In [103]:
pd.merge(emp1,Dept , on='Deptno', how='right')

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12.0,abc,7000.0,2002-02-02,10.0,medium pay,NaN,22.0,teen,7000.0,abc,bal
1,13.0,xyz,3000.0,2001-03-03,10.0,low pay,500.0,23.0,teen,3500.0,abc,bal
2,NaN,NaN,NaN,NaT,20.0,NaN,NaN,NaN,NaN,NaN,cbz,mum

In [104]:
pd.merge(emp1,Dept , on='Deptno', how='outer')

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12.0,abc,7000.0,2002-02-02,10.0,medium pay,NaN,22.0,teen,7000.0,abc,bal
1,13.0,xyz,3000.0,2001-03-03,10.0,low pay,500.0,23.0,teen,3500.0,abc,bal
2,NaN,NaN,NaN,NaT,20.0,NaN,NaN,NaN,NaN,NaN,cbz,mum

In [105]:
pd.merge(emp1,Dept , on='Deptno', how='inner')

,id,Name,Sal,Hiredate,Deptno,sal_grade,comm,age,age_category,income,dname,loc
0,12,abc,7000,2002-02-02,10,medium pay,NaN,22,teen,7000,abc,bal
1,13,xyz,3000,2001-03-03,10,low pay,500.0,23,teen,3500,abc,bal